[package]
name = "rand-image-method-rs"
version = "0.1.0"
authors = ["matthias"]
edition = "2018"

[lib]
name = "rust2py"
crate-type = ["cdylib"]

[dependencies.cpython]
version = "0.6"
features = ["extension-module"]
